# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KuanKanManHua' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'SDWebImage'
    
    pod 'MJPhotoBrowser'
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'JPFPSStatus'
    pod 'MJRefresh'
    pod 'JGProgressHUD'
    # Pods for KuanKanManHua
    
    target 'KuanKanManHuaTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'KuanKanManHuaUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
